/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SuiviRouteImport } from './routes/suivi'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as IngredientAnalyzerRouteImport } from './routes/ingredient-analyzer'
import { Route as FinishRouteImport } from './routes/finish'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CourseRouteImport } from './routes/course'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StartTokenRouteImport } from './routes/start.$token'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as AdminUnclassifiedRouteImport } from './routes/admin_.unclassified'
import { Route as AdminTokensRouteImport } from './routes/admin_.tokens'
import { Route as AdminTemplatesRouteImport } from './routes/admin_.templates'
import { Route as AdminRoutinesRouteImport } from './routes/admin_.routines'
import { Route as AdminProductsRouteImport } from './routes/admin_.products'
import { Route as AdminNutritionRouteImport } from './routes/admin_.nutrition'
import { Route as AdminNotificationsRouteImport } from './routes/admin_.notifications'
import { Route as AdminIngredientAnalyzerRouteImport } from './routes/admin_.ingredient-analyzer'
import { Route as AdminFaqRouteImport } from './routes/admin_.faq'
import { Route as AdminCourseEditorRouteImport } from './routes/admin_.course-editor'
import { Route as AdminAdminsRouteImport } from './routes/admin_.admins'
import { Route as AdminTemplatesIndexRouteImport } from './routes/admin_.templates.index'
import { Route as AdminTemplatesTemplateIdRouteImport } from './routes/admin_.templates.$templateId'
import { Route as AdminStudentUidRouteImport } from './routes/admin_.student.$uid'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviRoute = SuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientAnalyzerRoute = IngredientAnalyzerRouteImport.update({
  id: '/ingredient-analyzer',
  path: '/ingredient-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const FinishRoute = FinishRouteImport.update({
  id: '/finish',
  path: '/finish',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartTokenRoute = StartTokenRouteImport.update({
  id: '/start/$token',
  path: '/start/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnclassifiedRoute = AdminUnclassifiedRouteImport.update({
  id: '/admin_/unclassified',
  path: '/admin/unclassified',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTokensRoute = AdminTokensRouteImport.update({
  id: '/admin_/tokens',
  path: '/admin/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/admin_/templates',
  path: '/admin/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoutinesRoute = AdminRoutinesRouteImport.update({
  id: '/admin_/routines',
  path: '/admin/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin_/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNutritionRoute = AdminNutritionRouteImport.update({
  id: '/admin_/nutrition',
  path: '/admin/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin_/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIngredientAnalyzerRoute = AdminIngredientAnalyzerRouteImport.update({
  id: '/admin_/ingredient-analyzer',
  path: '/admin/ingredient-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/admin_/faq',
  path: '/admin/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCourseEditorRoute = AdminCourseEditorRouteImport.update({
  id: '/admin_/course-editor',
  path: '/admin/course-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admin_/admins',
  path: '/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesIndexRoute = AdminTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTemplatesRoute,
} as any)
const AdminTemplatesTemplateIdRoute =
  AdminTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => AdminTemplatesRoute,
  } as any)
const AdminStudentUidRoute = AdminStudentUidRouteImport.update({
  id: '/admin_/student/$uid',
  path: '/admin/student/$uid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/course': typeof CourseRoute
  '/faq': typeof FaqRoute
  '/finish': typeof FinishRoute
  '/ingredient-analyzer': typeof IngredientAnalyzerRoute
  '/intake': typeof IntakeRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/suivi': typeof SuiviRoute
  '/welcome': typeof WelcomeRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/course-editor': typeof AdminCourseEditorRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/ingredient-analyzer': typeof AdminIngredientAnalyzerRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/nutrition': typeof AdminNutritionRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/routines': typeof AdminRoutinesRoute
  '/admin/templates': typeof AdminTemplatesRouteWithChildren
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/unclassified': typeof AdminUnclassifiedRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/start/$token': typeof StartTokenRoute
  '/admin/student/$uid': typeof AdminStudentUidRoute
  '/admin/templates/$templateId': typeof AdminTemplatesTemplateIdRoute
  '/admin/templates/': typeof AdminTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/course': typeof CourseRoute
  '/faq': typeof FaqRoute
  '/finish': typeof FinishRoute
  '/ingredient-analyzer': typeof IngredientAnalyzerRoute
  '/intake': typeof IntakeRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/suivi': typeof SuiviRoute
  '/welcome': typeof WelcomeRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/course-editor': typeof AdminCourseEditorRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/ingredient-analyzer': typeof AdminIngredientAnalyzerRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/nutrition': typeof AdminNutritionRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/routines': typeof AdminRoutinesRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/unclassified': typeof AdminUnclassifiedRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/start/$token': typeof StartTokenRoute
  '/admin/student/$uid': typeof AdminStudentUidRoute
  '/admin/templates/$templateId': typeof AdminTemplatesTemplateIdRoute
  '/admin/templates': typeof AdminTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/course': typeof CourseRoute
  '/faq': typeof FaqRoute
  '/finish': typeof FinishRoute
  '/ingredient-analyzer': typeof IngredientAnalyzerRoute
  '/intake': typeof IntakeRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/suivi': typeof SuiviRoute
  '/welcome': typeof WelcomeRoute
  '/admin_/admins': typeof AdminAdminsRoute
  '/admin_/course-editor': typeof AdminCourseEditorRoute
  '/admin_/faq': typeof AdminFaqRoute
  '/admin_/ingredient-analyzer': typeof AdminIngredientAnalyzerRoute
  '/admin_/notifications': typeof AdminNotificationsRoute
  '/admin_/nutrition': typeof AdminNutritionRoute
  '/admin_/products': typeof AdminProductsRoute
  '/admin_/routines': typeof AdminRoutinesRoute
  '/admin_/templates': typeof AdminTemplatesRouteWithChildren
  '/admin_/tokens': typeof AdminTokensRoute
  '/admin_/unclassified': typeof AdminUnclassifiedRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/start/$token': typeof StartTokenRoute
  '/admin_/student/$uid': typeof AdminStudentUidRoute
  '/admin_/templates/$templateId': typeof AdminTemplatesTemplateIdRoute
  '/admin_/templates/': typeof AdminTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/course'
    | '/faq'
    | '/finish'
    | '/ingredient-analyzer'
    | '/intake'
    | '/journal'
    | '/login'
    | '/products'
    | '/profile'
    | '/register'
    | '/suivi'
    | '/welcome'
    | '/admin/admins'
    | '/admin/course-editor'
    | '/admin/faq'
    | '/admin/ingredient-analyzer'
    | '/admin/notifications'
    | '/admin/nutrition'
    | '/admin/products'
    | '/admin/routines'
    | '/admin/templates'
    | '/admin/tokens'
    | '/admin/unclassified'
    | '/lesson/$lessonId'
    | '/start/$token'
    | '/admin/student/$uid'
    | '/admin/templates/$templateId'
    | '/admin/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/course'
    | '/faq'
    | '/finish'
    | '/ingredient-analyzer'
    | '/intake'
    | '/journal'
    | '/login'
    | '/products'
    | '/profile'
    | '/register'
    | '/suivi'
    | '/welcome'
    | '/admin/admins'
    | '/admin/course-editor'
    | '/admin/faq'
    | '/admin/ingredient-analyzer'
    | '/admin/notifications'
    | '/admin/nutrition'
    | '/admin/products'
    | '/admin/routines'
    | '/admin/tokens'
    | '/admin/unclassified'
    | '/lesson/$lessonId'
    | '/start/$token'
    | '/admin/student/$uid'
    | '/admin/templates/$templateId'
    | '/admin/templates'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/course'
    | '/faq'
    | '/finish'
    | '/ingredient-analyzer'
    | '/intake'
    | '/journal'
    | '/login'
    | '/products'
    | '/profile'
    | '/register'
    | '/suivi'
    | '/welcome'
    | '/admin_/admins'
    | '/admin_/course-editor'
    | '/admin_/faq'
    | '/admin_/ingredient-analyzer'
    | '/admin_/notifications'
    | '/admin_/nutrition'
    | '/admin_/products'
    | '/admin_/routines'
    | '/admin_/templates'
    | '/admin_/tokens'
    | '/admin_/unclassified'
    | '/lesson/$lessonId'
    | '/start/$token'
    | '/admin_/student/$uid'
    | '/admin_/templates/$templateId'
    | '/admin_/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CourseRoute: typeof CourseRoute
  FaqRoute: typeof FaqRoute
  FinishRoute: typeof FinishRoute
  IngredientAnalyzerRoute: typeof IngredientAnalyzerRoute
  IntakeRoute: typeof IntakeRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SuiviRoute: typeof SuiviRoute
  WelcomeRoute: typeof WelcomeRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminCourseEditorRoute: typeof AdminCourseEditorRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminIngredientAnalyzerRoute: typeof AdminIngredientAnalyzerRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminNutritionRoute: typeof AdminNutritionRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRoutinesRoute: typeof AdminRoutinesRoute
  AdminTemplatesRoute: typeof AdminTemplatesRouteWithChildren
  AdminTokensRoute: typeof AdminTokensRoute
  AdminUnclassifiedRoute: typeof AdminUnclassifiedRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
  StartTokenRoute: typeof StartTokenRoute
  AdminStudentUidRoute: typeof AdminStudentUidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi': {
      id: '/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof SuiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredient-analyzer': {
      id: '/ingredient-analyzer'
      path: '/ingredient-analyzer'
      fullPath: '/ingredient-analyzer'
      preLoaderRoute: typeof IngredientAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finish': {
      id: '/finish'
      path: '/finish'
      fullPath: '/finish'
      preLoaderRoute: typeof FinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/$token': {
      id: '/start/$token'
      path: '/start/$token'
      fullPath: '/start/$token'
      preLoaderRoute: typeof StartTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/unclassified': {
      id: '/admin_/unclassified'
      path: '/admin/unclassified'
      fullPath: '/admin/unclassified'
      preLoaderRoute: typeof AdminUnclassifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/tokens': {
      id: '/admin_/tokens'
      path: '/admin/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof AdminTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/templates': {
      id: '/admin_/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/routines': {
      id: '/admin_/routines'
      path: '/admin/routines'
      fullPath: '/admin/routines'
      preLoaderRoute: typeof AdminRoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/products': {
      id: '/admin_/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/nutrition': {
      id: '/admin_/nutrition'
      path: '/admin/nutrition'
      fullPath: '/admin/nutrition'
      preLoaderRoute: typeof AdminNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/notifications': {
      id: '/admin_/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/ingredient-analyzer': {
      id: '/admin_/ingredient-analyzer'
      path: '/admin/ingredient-analyzer'
      fullPath: '/admin/ingredient-analyzer'
      preLoaderRoute: typeof AdminIngredientAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/faq': {
      id: '/admin_/faq'
      path: '/admin/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/course-editor': {
      id: '/admin_/course-editor'
      path: '/admin/course-editor'
      fullPath: '/admin/course-editor'
      preLoaderRoute: typeof AdminCourseEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/admins': {
      id: '/admin_/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/templates/': {
      id: '/admin_/templates/'
      path: '/'
      fullPath: '/admin/templates/'
      preLoaderRoute: typeof AdminTemplatesIndexRouteImport
      parentRoute: typeof AdminTemplatesRoute
    }
    '/admin_/templates/$templateId': {
      id: '/admin_/templates/$templateId'
      path: '/$templateId'
      fullPath: '/admin/templates/$templateId'
      preLoaderRoute: typeof AdminTemplatesTemplateIdRouteImport
      parentRoute: typeof AdminTemplatesRoute
    }
    '/admin_/student/$uid': {
      id: '/admin_/student/$uid'
      path: '/admin/student/$uid'
      fullPath: '/admin/student/$uid'
      preLoaderRoute: typeof AdminStudentUidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminTemplatesRouteChildren {
  AdminTemplatesTemplateIdRoute: typeof AdminTemplatesTemplateIdRoute
  AdminTemplatesIndexRoute: typeof AdminTemplatesIndexRoute
}

const AdminTemplatesRouteChildren: AdminTemplatesRouteChildren = {
  AdminTemplatesTemplateIdRoute: AdminTemplatesTemplateIdRoute,
  AdminTemplatesIndexRoute: AdminTemplatesIndexRoute,
}

const AdminTemplatesRouteWithChildren = AdminTemplatesRoute._addFileChildren(
  AdminTemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CourseRoute: CourseRoute,
  FaqRoute: FaqRoute,
  FinishRoute: FinishRoute,
  IngredientAnalyzerRoute: IngredientAnalyzerRoute,
  IntakeRoute: IntakeRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SuiviRoute: SuiviRoute,
  WelcomeRoute: WelcomeRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminCourseEditorRoute: AdminCourseEditorRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminIngredientAnalyzerRoute: AdminIngredientAnalyzerRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminNutritionRoute: AdminNutritionRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRoutinesRoute: AdminRoutinesRoute,
  AdminTemplatesRoute: AdminTemplatesRouteWithChildren,
  AdminTokensRoute: AdminTokensRoute,
  AdminUnclassifiedRoute: AdminUnclassifiedRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
  StartTokenRoute: StartTokenRoute,
  AdminStudentUidRoute: AdminStudentUidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
